name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  kind:
    env:
      KUBECONFIG: /tmp/kube-config
      KUBE_CONFIG: /tmp/kube-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make our image
        run: make docker
      - name: Create kind cluster
        uses: helm/kind-action@v1.11.0
        with:
          cluster_name: kind
          node_image: kindest/node:v1.27.3
      - name: Deploy certificate signing request
        run: kubectl apply -f test/certs.yaml
      - name: Deploy certificate signing request
        run: kubectl apply -f test/certs2.yaml
      - name: Approve our certificate signing request
        run: kubectl certificate approve operator
      - name: register our image
        run: kind load docker-image gameboysuits:dev --name kind
      - name: Deploy collector
        run: kubectl apply -f test/collector.yaml
      - name: Deploy operator collector CRDs
        run: kubectl apply -f test/crd-opentelemetrycollector.yaml
      - name: Sleep 10s
        run: sleep 10
      - name: Deploy operator instrumentation CRDs
        run: kubectl apply -f test/crd-opentelemetryinstrumentation.yaml
      - name: Deploy operator opampbridge CRDs
        run: kubectl apply -f test/crd-opampbridges.yaml
      - name: Deploy instrumentation
        run: kubectl apply -f test/instrumentation.yaml
      - name: Sleep 10s
        run: sleep 10
      - name: Deploy operator
        run: kubectl apply -f test/operator.yaml
      - name: Sleep 10s
        run: sleep 10
      - name: Deploy java app
        run: kubectl apply -f test/java.yaml
      - name: Sleep 20s
        run: sleep 20
      - name: Check logs
        run: |
          COLLECTOR_POD=$(kubectl get pod -l app=collector -o jsonpath="{.items[0].metadata.name}")
          LOGS=$(kubectl logs ${COLLECTOR_POD})
          echo ${LOGS}
          echo ${LOGS} | grep "Starting Servlet engine"

